---
title: "Michelle Lui Resume"
output: 
  html_document:
    toc: true
    toc_float: true
---

* EDUCATION
  * Columbia University, Mailman School of Public Health
    * Masters of Public Health (August 2019 - May 2021)
      * Concentration: Epidemiology, Certificate: Applied Biostatistics
  * University of California, Berkeley 
    * (August 2015 - May 2019)	
      * Majors: B.A. Molecular and Cell Biology: Immunology (Infectious Disease track), B.A. Public Health, Minor: Music
* EXPERIENCES AND ACTIVITIES
  * New York City Department of Health and Mental Hygiene
    * Data Analysis Intern (July 2020 - Present)
      * Use SAS and GIS to analyze 2019 data on babesiosis, anaplasmosis, ehrlichiosis, RMSF, and rickettsialpox
      * Write summary reports, participate in Bureau-wide investigations, assist with surveillance tasks as needed
  * CIPHER (Citizen’s Public Health Literacy)
    * Intern/Volunteer (June 2020- present)
      * Assist in creating curriculum directed at increasing health equity in the Washington Heights community through dissemination of accessible health information related to Covid-19
      * Conduct literature reviews, provide resources for curriculum and community needs assessment, grant writing, pre- post- test program evaluation
  * Columbia University Mailman School of Public Health
    * Research Assistant (February 2020 – present), PI: Dr. Lauren Houghton
      * Conduct literature reviews, assist in research protocol development and implementation
  * Health Plan of San Mateo
    * Intern (Summer 2019)
      * Research and provide data to launch a Park Rx program for Medicaid patients within the San Mateo County clinics
      * Interview key internal and external stakeholders, made recommendations for best program implementation practices
* SKILLS
  * Microsoft Office (Word, Excel, Powerpoint, Access), Python, SQL, SAS, R, GIS, patient education, basic laboratory skills (chemistry, biology, immunology), Zotero, fundraising, marketing 
      