---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
```

```{r}
data("instacart")

instacart = 
  instacart %>%
  filter(
    reordered == 0,
    order_hour_of_day == 8,
    order_dow == 6) %>%
  select(add_to_cart_order, reordered, user_id, order_dow, order_hour_of_day, product_name, aisle, department, days_since_prior_order) 
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
instacart %>%
  plot_ly(x = ~aisle, y = ~add_to_cart_order, color = ~department, type = "box", colors = "viridis") %>%
  layout(title = 'Order that product was added to cart by aisle ',
      xaxis = list(title = 'Aisle'),
      yaxis = list(title = 'Add to cart order'))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
instacart %>%
  mutate(text_label = str_c("Product:", product_name, "\nAisle:", aisle)) %>%
  plot_ly(
    x = ~days_since_prior_order, y = ~add_to_cart_order, color = ~aisle, text = ~text_label, alpha = .5,
    type = "scatter", mode = "markers", colors = "viridis") %>%
  layout(title = 'Days since prior order versus Order added to cart',
         xaxis = list(title = 'Days since prior order'),
         yaxis = list(title = 'Add to cart order'))
```

### Chart C

```{r}
instacart %>%
  count(department) %>%
  mutate(department = fct_reorder(department, n)) %>%
  plot_ly(x = ~department, y = ~n, color = ~department, type = "bar", colors = "viridis") %>%
  layout(title = 'Amount ordered by Department ',
    xaxis = list(title = 'Department'),
    yaxis = list(title = 'Amount ordered'))
```

